#!/usr/bin/env bash
# Script that displays numbers 1-100. Replaces any number with FizzBuzz for which are a multiple of both 3 and 5, Fizz for multiples of 3 and Buzz for multiples of 5. Any other numbers displayed as is.

count=1
while [ $count -ne 101 ]
do
	if [ $((count % 15)) -eq 0  ]
	then
		echo "FizzBuzz"
	elif [ $((count % 3)) -eq 0 ]
	then echo "Fizz"
	elif [ $((count % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo $count
	fi
	((count++))
done
