#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20 and:

i=1
while (( i<=20 ))
do
	echo "$i"
	case $i in
		4) echo "bad luck from China";;
		9) echo "bad luck form Japan";;
		17) echo "bad luck from Italy";;
	esac
	(( i++ ))
done 

