#!/usr/bin/env bash
# Script that manages by process manage_my_process. Eisther starting, stopping or restarting the other process and creating a file storing its PID.

var1="/var/run/my_process.pid"
if [ "$1" == "start" ]
then
	echo "manage_my_process started" #Also job number, PID store in pid file
	./manage_my_process &
	echo "$!" > "$var1"

elif [ "$1" == "stop" ]
then
	echo "manage_my_process stopped" #And .pid file delete
	sudo pkill -f "./manage_my_process"
	rm "$var1"

elif [ "$1" == "restart" ]
then
	echo "manage_my_process restarted"
	sudo pkill -f "./manage_my_process"
	rm "$var1"
	./manage_my_process &
	echo "$!" > "$var1"
else
	echo "usage: manage_my_process {start|stop|restart}"
fi
