#!/usr/bin/env bash
# Script that prints 'To infinity and beyond' indefinitely with a sleep 2 and prints 'I am invincible!!!' when it terminates.

trap "echo 'I am invincible!!!'" 15

while :
do
	echo "To infinity and beyond"
	sleep 2
done
